server:
  port: 8081

spring:
  application:
    name: SpringTestS2

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    default-schema: spring_test_s2